### ISSUE TITLE
How it works

### ISSUE THREAD

**Issue by szepeviktor** [sj-i/typist#2]
Please consider adding a section to the README how this package works.
Thank you.

**Comment by szepeviktor** [comment]
I mean a bit deeper than

>  It internally uses references to typed properties introduced in PHP 7.4.

**Comment by sj-i** [comment]
OK, I'll try it later. Thanks!!!!

**Comment by RikudouSage** [comment]
The methods inside `Typist\Typist` class (`bool()`, `int()` etc.) take the variable passed as reference as the first argument and a value as the second argument. Inside the method your variable (passed by reference) is passed to another class that contains a private typed property (e.g. `bool` for the class `Typist\BoolEnforcer` which is returned by `Typist\Typist::bool()`).

Since the variable was passed by reference, the typed property is pointing to the same memory as your local variable. If you change the value of your local variable, you also change the value of the typed property and if you provide invalid type, the php engine will throw a `TypeError` because you tried to assign an invalid type to a typed property.

**Comment by szepeviktor** [comment]
@sj-i Could add this/a part of this to README?

**Comment by sj-i** [comment]
@szepeviktor Added a bit of explanations [here](https://github.com/sj-i/typist/blob/b36ffa4fbcf0ef75208225368a1351b673fbd61f/README.md#how-it-works)!
Ooops, but it seems that I made an unnecessary challenge to English!

@RikudouSage Thanks for your clear and succinct great explanation!

**Comment by szepeviktor** [comment]
Thank you.
